var keyMirror = require('keymirror');

module.exports = keyMirror({
    /* Database - Notebook */
    NOTEBOOK_DATABASE_LOADTREE: null,
    NOTEBOOK_DATABASE_LOADTREE_SUCCESS: null,
    NOTEBOOK_DATABASE_LOADTREE_ERROR: null,
    NOTEBOOK_DATABASE_SAVETREE: null,
    NOTEBOOK_DATABASE_SAVETREE_SUCCESS: null,
    NOTEBOOK_DATABASE_SAVETREE_ERROR: null,
    NOTEBOOK_DATABASE_CREATE_STACK: null,
    NOTEBOOK_DATABASE_CREATE_NOTEBOOK: null,
    NOTEBOOK_DATABASE_CREATE_NOTEBOOK_SUCCESS: null,
    NOTEBOOK_DATABASE_CREATE_NOTEBOOK_ERROR: null,
    NOTEBOOK_DATABASE_TRASH_NOTEBOOK: null,
    NOTEBOOK_DATABASE_TRASH_NOTEBOOK_SUCCESS: null,
    NOTEBOOK_DATABASE_TRASH_NOTEBOOK_ERROR: null,
    NOTEBOOK_DATABASE_SELECT_NOTEBOOK: null,

    /* Database - Note */
    NOTEBOOK_DATABASE_LOADNOTES: null,
    NOTEBOOK_DATABASE_LOADNOTES_SUCCESS: null,
    NOTEBOOK_DATABASE_LOADNOTES_ERROR: null,
    NOTEBOOK_DATABASE_SELECT_NOTE: null,
    NOTEBOOK_DATABASE_SET_NOTE_SORT_METHOD: null,
    NOTEBOOK_DATABASE_ADD_NOTE: null,
    NOTEBOOK_DATABASE_ADD_NOTE_SUCCESS: null,
    NOTEBOOK_DATABASE_ADD_NOTE_ERROR: null,
    NOTEBOOK_DATABASE_COPY_NOTE: null,
    NOTEBOOK_DATABASE_COPY_NOTE_SUCCESS: null,
    NOTEBOOK_DATABASE_COPY_NOTE_ERROR: null,
    NOTEBOOK_DATABASE_TRASH_NOTE: null,
    NOTEBOOK_DATABASE_TRASH_NOTE_SUCCESS: null,
    NOTEBOOK_DATABASE_TRASH_NOTE_ERROR: null
});
