var keyMirror = require('keymirror');

module.exports = keyMirror({
    NOTEBOOK_APP_STORAGE_LIST: null,
    NOTEBOOK_APP_STORAGE_ADD: null,
    NOTEBOOK_APP_STORAGE_REMOVE: null,
    NOTEBOOK_APP_STORAGE_SET_DISK_INUSE: null,
    NOTEBOOK_APP_DATABASE_LOADTREE: null,
    NOTEBOOK_APP_DATABASE_LOADTREE_SUCCESS: null,
    NOTEBOOK_APP_DATABASE_LOADTREE_ERROR: null
});
