var keyMirror = require('keymirror');

module.exports = keyMirror({
    APP_MANAGER_LIST: null,
    APP_MANAGER_INSTALL: null,
    APP_MANAGER_INSTALL_UPLOADING: null,
    APP_MANAGER_INSTALL_INSTALLING: null,
    APP_MANAGER_INSTALL_SUCCESS: null,
    APP_MANAGER_INSTALL_FAIL: null,
    APP_MANAGER_UNINSTALL: null,
    APP_MANAGER_UNINSTALL_SUCCESS: null,
    APP_MANAGER_UNINSTALL_FAIL: null,
    APP_MANAGER_CANCEL_INSTALL: null,
    APP_MANAGER_CANCEL_INSTALL_SUCCESS: null,
    APP_MANAGER_CANCEL_INSTALL_FAIL: null
});
